// Generated by the WOLips Templateengine Plug-in at 14-gen-2014 11.13.54
package it.xplants.xtro.vgi;

import org.apache.log4j.Logger;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;

import er.extensions.appserver.ERXResponse;
import it.xplants.xtro.appserver.XTDirectAction;

public class DirectAction extends XTDirectAction {
	private static final Logger log = Logger.getLogger(DirectAction.class);

	public DirectAction(WORequest request) {
		super(request);

	}

	@Override
	public WOActionResults defaultAction() {
		return new ERXResponse(200);
	}

	@Override
	public WOActionResults viewSectionAction() {
		return defaultAction();
	}

	@Override
	public WOActionResults viewSiteAction() {
		return defaultAction();
	}

	@Override
	public WOActionResults viewContentAction() {
		return defaultAction();
	}
}
