// Generated by the WOLips Templateengine Plug-in at 14-gen-2014 11.13.54 by xPlants.it SRL
package it.xplants.xtro.vgi.components;

import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

public class Main extends ERXComponent {
	public Main(WOContext context) {
		super(context);
	}
}
