name: Release AWS
on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Specify the stage to deploy"
        required: true
        default: "preprod"

jobs:
  buildAndDeploy:
    name: BuildAndDeploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: ${{ github.event.inputs.stage }}
    env:
      ENV: ${{ github.event.inputs.stage }}
      APP_NAME: stock
      S3_BUCKET_NAME: ${{ github.event.inputs.stage }}-pallino-stock
      S3_FILE_NAME: ${{ github.event.inputs.stage }}-stock-${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"

      - name: Build with Maven
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B package --file pom.xml 
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}